---
title: "Tidy Data"
output: github_document
date: "2022-09-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
options(tibble.print_min = 5)
```

### Using `pivot_longer`
```{r}
pulse_df <- haven::read_sas('data/public_pulse_data.sas7bdat') %>%
  janitor::clean_names(pulse_df)
```
Data shows ID, age at baseline, sex, and depression scores. Data is not tidy.
We want to `pivot_longer`, take those columnns, stack them on top of each other, and create a new variable that indicates what visit we're at.

```{r}
pulse_tidy_data <-
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  )
```
`names_prefix` --> drops whatever you list in quotes.

### Doing things in one swoop + `mutate`
```{r}
pulse_df <- haven::read_sas('data/public_pulse_data.sas7bdat') %>%
  janitor::clean_names() %>% 
    pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m"),
    visit = factor(visit)
  ) %>% 
  arrange(id, visit)
```


### Learning Assessment: Litters Data
```{r}
litters_df <- read_csv('data/FAS_litters.csv') %>% 
  janitor::clean_names()

litters_tidy_df <- litters_df %>% 
  select(litter_number, gd0_weight, gd18_weight) %>% 
  pivot_longer(
    c(gd0_weight, gd18_weight),
    names_to = "gd",
    values_to = "weight"
  ) %>% 
  mutate(
    gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```


